site_name: Prosa aristonoetica

repo_url: https://github.com/IL01DI/docs
repo_name: IL01DI/docs
edit_uri: edit/main/docs

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs

markdown_extensions:
  - nl2br
  - pymdownx.details
  - pymdownx.superfences
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-committers:
      repository: IL01DI/docs
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - propaedeutica:
    - sophia/propaedeutica/sapientia.md
    - sophia/propaedeutica/philosophia.md
  - hermeneutica:
    - sophia/dialectica/Plato/Hippias Major.md
  - mathematica:
    - sophia/mathematica/Plato.md
    - sophia/mathematica/Aristoteles.md
    - sophia/mathematica/Kant.md
    - sophia/mathematica/Hegel.md
    - sophia/mathematica/Nietzsche.md
  - dialectica:
    - sophia/dialectica/Plato.md
  - metaphysica: f.md